In [1]:
import pandas as pd

m_store = pd.read_csv("m_store.csv", header=0)
m_store

     store_id store_name area_cd
0           1        昭島店      TK
1           2      あきる野店      TK
2           3        足立店      TK
3           4       北千住店      TK
4           5        綾瀬店      TK
..        ...        ...     ...
192       193        桐生店      GU
193       194        高崎店      GU
194       195        館林店      GU
195       196        前橋店      GU
196       999       保守担当      TK

[197 rows x 3 columns]

In [2]:
m_area = pd.read_csv("m_area.csv", header=0)
m_area

  area_cd wide_area narrow_area
0      TK        東京          東京
1      KN       神奈川         神奈川
2      CH        千葉          千葉
3      SA        埼玉          埼玉
4      IB       北関東          茨城
5      TO       北関東          栃木
6      GU       北関東          群馬

In [3]:
tbl_order_4 = pd.read_csv("tbl_order_202004.csv", header=0)
tbl_order_4

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
233255,25546308,3,C24617924,46,3700904,2020-04-30 21:58:58,2020-04-30 22:19:58,0,2615,2
233256,91693481,45,C68997855,6,37852755,2020-04-30 21:58:58,2020-04-30 22:13:58,0,2732,2
233257,57908119,36,C16123702,81,90372382,2020-04-30 21:58:58,2020-04-30 22:47:58,0,2363,2
233258,7145625,174,C80733640,75,48265986,2020-04-30 21:58:58,2020-04-30 22:32:58,0,2238,2
233259,31301192,151,C23758178,9,13847510,2020-04-30 21:58:58,2020-04-30 22:52:58,0,1900,2

In [4]:
tbl_order_5 = pd.read_csv("tbl_order_202005.csv", header=0)
tbl_order_5

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,24742472,22,C90731046,22,80308413,2020-05-01 11:00:00,2020-05-01 11:22:00,1,2328,1
1,11342919,56,C68678177,12,35725624,2020-05-01 11:00:00,2020-05-01 11:50:00,0,2987,2
2,76451864,56,C79630016,46,2609869,2020-05-01 11:00:00,2020-05-01 11:32:00,0,2603,2
3,28392539,192,C83895707,80,17111162,2020-05-01 11:00:00,2020-05-01 11:19:00,0,2603,2
4,71706591,121,C36584528,93,22800835,2020-05-01 11:00:00,2020-05-01 11:17:00,0,2877,2
...,...,...,...,...,...,...,...,...,...,...
241134,47039360,154,C39765066,90,27121351,2020-05-31 21:58:58,2020-05-31 22:42:58,1,2363,1
241135,61054188,94,C19465010,41,61513298,2020-05-31 21:58:58,2020-05-31 22:40:58,0,2112,2
241136,45288914,11,C23883838,40,65359139,2020-05-31 21:58:58,2020-05-31 22:38:58,0,3838,2
241137,41608372,149,C48350551,43,42138977,2020-05-31 21:58:58,2020-05-31 22:52:58,0,1899,2
241138,40316733,169,C49087342,61,59737067,2020-05-31 21:58:58,2020-05-31 22:08:58,0,3901,2

In [5]:
order_all = pd.concat([tbl_order_4, tbl_order_5], ignore_index=True)
order_all

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,79339111,49,C26387220,50,67393872,2020-04-01 11:00:00,2020-04-01 11:18:00,1,4144,1
1,18941733,85,C48773811,26,91834983,2020-04-01 11:00:00,2020-04-01 11:22:00,0,2877,2
2,56217880,76,C66287421,36,64409634,2020-04-01 11:00:00,2020-04-01 11:15:00,0,2603,2
3,28447783,190,C41156423,19,73032165,2020-04-01 11:00:00,2020-04-01 11:16:00,0,2732,2
4,32576156,191,C54568117,71,23281182,2020-04-01 11:00:00,2020-04-01 11:53:00,0,2987,2
...,...,...,...,...,...,...,...,...,...,...
474394,47039360,154,C39765066,90,27121351,2020-05-31 21:58:58,2020-05-31 22:42:58,1,2363,1
474395,61054188,94,C19465010,41,61513298,2020-05-31 21:58:58,2020-05-31 22:40:58,0,2112,2
474396,45288914,11,C23883838,40,65359139,2020-05-31 21:58:58,2020-05-31 22:38:58,0,3838,2
474397,41608372,149,C48350551,43,42138977,2020-05-31 21:58:58,2020-05-31 22:52:58,0,1899,2
474398,40316733,169,C49087342,61,59737067,2020-05-31 21:58:58,2020-05-31 22:08:58,0,3901,2

In [6]:
import glob

tbl_files = glob.glob("tbl_order_*.csv")

In [7]:
order_all = pd.DataFrame()

for file in tbl_files:
    order_all = pd.concat([order_all, pd.read_csv(file)], axis=0, ignore_index=True)
    print(file)
order_all

tbl_order_202006.csv
tbl_order_202004.csv
tbl_order_202005.csv

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2
1,28342394,12,C98307866,98,46924304,2020-06-01 11:00:00,2020-06-01 11:52:00,0,2064,2
2,29799587,174,C59484037,45,47054474,2020-06-01 11:00:00,2020-06-01 11:25:00,0,3900,2
3,96960753,23,C57278332,70,60848267,2020-06-01 11:00:00,2020-06-01 11:45:00,0,2750,2
4,52147209,7,C36890849,80,20633593,2020-06-01 11:00:00,2020-06-01 11:23:00,0,2328,2
...,...,...,...,...,...,...,...,...,...,...
707695,47039360,154,C39765066,90,27121351,2020-05-31 21:58:58,2020-05-31 22:42:58,1,2363,1
707696,61054188,94,C19465010,41,61513298,2020-05-31 21:58:58,2020-05-31 22:40:58,0,2112,2
707697,45288914,11,C23883838,40,65359139,2020-05-31 21:58:58,2020-05-31 22:38:58,0,3838,2
707698,41608372,149,C48350551,43,42138977,2020-05-31 21:58:58,2020-05-31 22:52:58,0,1899,2
707699,40316733,169,C49087342,61,59737067,2020-05-31 21:58:58,2020-05-31 22:08:58,0,3901,2

In [8]:
order_all.isna().sum(axis=0)

order_id             0
store_id             0
customer_id          0
coupon_cd            0
sales_detail_id      0
order_accept_date    0
delivered_date       0
takeout_flag         0
total_amount         0
status               0
dtype: int64

In [9]:
order_all.describe(include="all")

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
count,7.077000e+05,707700.000000,707700,707700.000000,7.077000e+05,707700,707700,707700.000000,707700.000000,707700.000000
unique,NaN,NaN,41602,NaN,NaN,59058,631199,NaN,NaN,NaN
top,NaN,NaN,C64592879,NaN,NaN,2020-04-30 13:11:11,2020-06-02 15:29:02,NaN,NaN,NaN
freq,NaN,NaN,113,NaN,NaN,32,5,NaN,NaN,NaN
mean,5.000989e+07,103.934565,NaN,49.514363,5.000335e+07,NaN,NaN,0.259864,2960.651814,3.082908
std,2.889226e+07,86.374451,NaN,28.882605,2.885575e+07,NaN,NaN,0.438560,954.378771,2.836278
min,2.200000e+01,1.000000,NaN,0.000000,4.600000e+01,NaN,NaN,0.000000,698.000000,1.000000
25%,2.501247e+07,51.000000,NaN,25.000000,2.504502e+07,NaN,NaN,0.000000,2308.000000,2.000000
50%,4.999655e+07,99.000000,NaN,49.000000,5.004506e+07,NaN,NaN,0.000000,2808.000000,2.000000
75%,7.508014e+07,148.000000,NaN,75.000000,7.499707e+07,NaN,NaN,1.000000,3617.000000,2.000000
max,9.999980e+07,999.000000,NaN,99.000000,9.999965e+07,NaN,NaN,1.000000,5100.000000,9.000000

In [10]:
order_all["order_accept_date"] = pd.to_datetime(order_all["order_accept_date"])
order_all["delivered_date"] = pd.to_datetime(order_all["delivered_date"])
order_all[["order_accept_date", "delivered_date"]].describe()

                   order_accept_date                 delivered_date
count                         707700                         707700
mean   2020-05-16 16:30:26.256043776  2020-05-16 17:04:47.210007040
min              2020-04-01 11:00:00            2020-04-01 11:10:00
25%              2020-04-23 19:15:15            2020-04-23 19:47:50
50%              2020-05-16 16:33:33            2020-05-16 17:07:04
75%              2020-06-08 13:40:40  2020-06-08 14:15:29.249999872
max              2020-06-30 21:58:58            2020-06-30 22:55:56

In [11]:
order_all.describe(include="all")

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
count,7.077000e+05,707700.000000,707700,707700.000000,7.077000e+05,707700,707700,707700.000000,707700.000000,707700.000000
unique,NaN,NaN,41602,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,C64592879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5.000989e+07,103.934565,NaN,49.514363,5.000335e+07,2020-05-16 16:30:26.256043776,2020-05-16 17:04:47.210007040,0.259864,2960.651814,3.082908
min,2.200000e+01,1.000000,NaN,0.000000,4.600000e+01,2020-04-01 11:00:00,2020-04-01 11:10:00,0.000000,698.000000,1.000000
25%,2.501247e+07,51.000000,NaN,25.000000,2.504502e+07,2020-04-23 19:15:15,2020-04-23 19:47:50,0.000000,2308.000000,2.000000
50%,4.999655e+07,99.000000,NaN,49.000000,5.004506e+07,2020-05-16 16:33:33,2020-05-16 17:07:04,0.000000,2808.000000,2.000000
75%,7.508014e+07,148.000000,NaN,75.000000,7.499707e+07,2020-06-08 13:40:40,2020-06-08 14:15:29.249999872,1.000000,3617.000000,2.000000
max,9.999980e+07,999.000000,NaN,99.000000,9.999965e+07,2020-06-30 21:58:58,2020-06-30 22:55:56,1.000000,5100.000000,9.000000
std,2.889226e+07,86.374451,NaN,28.882605,2.885575e+07,NaN,NaN,0.438560,954.378771,2.836278

In [12]:
order_all = order_all[order_all["store_id"] != 999]
order_all.describe(include="all")

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status
count,7.038800e+05,703880.000000,703880,703880.000000,7.038800e+05,703880,703880,703880.000000,703880.000000,703880.000000
unique,NaN,NaN,41336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,C64592879,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5.001673e+07,99.076990,NaN,49.516098,5.000004e+07,2020-05-16 16:30:22.453871104,2020-05-16 17:04:43.259690496,0.259872,2959.949248,3.082704
min,2.200000e+01,1.000000,NaN,0.000000,4.600000e+01,2020-04-01 11:00:00,2020-04-01 11:10:00,0.000000,698.000000,1.000000
25%,2.501570e+07,51.000000,NaN,25.000000,2.504034e+07,2020-04-23 19:15:15,2020-04-23 19:48:01.750000128,0.000000,2308.000000,2.000000
50%,5.000930e+07,99.000000,NaN,49.000000,5.004219e+07,2020-05-16 16:33:33,2020-05-16 17:06:56,0.000000,2808.000000,2.000000
75%,7.508612e+07,147.000000,NaN,75.000000,7.499172e+07,2020-06-08 13:40:40,2020-06-08 14:15:20.249999872,1.000000,3617.000000,2.000000
max,9.999980e+07,196.000000,NaN,99.000000,9.999965e+07,2020-06-30 21:58:58,2020-06-30 22:55:56,1.000000,5100.000000,9.000000
std,2.889339e+07,55.942693,NaN,28.882841,2.885464e+07,NaN,NaN,0.438565,954.367273,2.836106

In [13]:
order_data = pd.merge(order_all, m_store, on="store_id", how="inner")
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2,西東京店,TK
1,12865494,64,C14333370,37,53426913,2020-06-01 11:34:34,2020-06-01 12:15:34,1,3865,1,西東京店,TK
2,83379185,64,C71117940,93,4241579,2020-06-01 11:39:39,2020-06-01 12:18:39,0,3742,2,西東京店,TK
3,75647324,64,C98875469,35,28001375,2020-06-01 11:40:40,2020-06-01 11:51:40,0,2112,2,西東京店,TK
4,61658367,64,C97997460,27,19753684,2020-06-01 11:58:58,2020-06-01 12:29:58,0,698,2,西東京店,TK
...,...,...,...,...,...,...,...,...,...,...,...,...
703875,45751697,121,C61543054,65,8810874,2020-05-31 20:40:40,2020-05-31 21:10:40,0,4133,2,港南店,KN
703876,17010970,121,C09116348,41,78734454,2020-05-31 20:57:57,2020-05-31 21:12:57,0,3742,2,港南店,KN
703877,6410294,121,C33037288,27,38602995,2020-05-31 21:13:13,2020-05-31 22:09:13,1,2677,1,港南店,KN
703878,17390187,121,C27745170,93,6889003,2020-05-31 21:30:30,2020-05-31 22:19:30,1,1882,9,港南店,KN
703879,5128945,121,C95085705,27,755093,2020-05-31 21:39:39,2020-05-31 22:21:39,0,4692,9,港南店,KN

In [14]:
order_data = pd.merge(order_data, m_area, on="area_cd", how="inner")
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2,西東京店,TK,東京,東京
1,12865494,64,C14333370,37,53426913,2020-06-01 11:34:34,2020-06-01 12:15:34,1,3865,1,西東京店,TK,東京,東京
2,83379185,64,C71117940,93,4241579,2020-06-01 11:39:39,2020-06-01 12:18:39,0,3742,2,西東京店,TK,東京,東京
3,75647324,64,C98875469,35,28001375,2020-06-01 11:40:40,2020-06-01 11:51:40,0,2112,2,西東京店,TK,東京,東京
4,61658367,64,C97997460,27,19753684,2020-06-01 11:58:58,2020-06-01 12:29:58,0,698,2,西東京店,TK,東京,東京
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703875,10044453,196,C22536742,29,18512545,2020-05-31 18:46:46,2020-05-31 18:56:46,1,3901,1,前橋店,GU,北関東,群馬
703876,69461367,196,C33554836,87,99552096,2020-05-31 19:21:21,2020-05-31 19:54:21,1,1927,1,前橋店,GU,北関東,群馬
703877,48225714,196,C33554836,96,22365732,2020-05-31 21:03:03,2020-05-31 21:33:03,0,2615,2,前橋店,GU,北関東,群馬
703878,76183473,196,C33554836,76,72014484,2020-05-31 21:04:04,2020-05-31 21:42:04,0,4659,2,前橋店,GU,北関東,群馬
703879,95868903,196,C07335754,12,78947363,2020-05-31 21:42:42,2020-05-31 22:24:42,0,2677,2,前橋店,GU,北関東,群馬

In [15]:
order_data.isna().sum()

order_id             0
store_id             0
customer_id          0
coupon_cd            0
sales_detail_id      0
order_accept_date    0
delivered_date       0
takeout_flag         0
total_amount         0
status               0
store_name           0
area_cd              0
wide_area            0
narrow_area          0
dtype: int64

In [16]:
order_data.loc[order_data["takeout_flag"] == 0, "takeout_name"] = "デリバリー"
order_data.loc[order_data["takeout_flag"] == 1, "takeout_name"] = "お持ち帰り"

In [17]:
order_data["takeout_name"] = order_data["takeout_flag"].map({0: "デリバリ", 1: "お持ち帰り"})
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area,takeout_name
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2,西東京店,TK,東京,東京,デリバリ
1,12865494,64,C14333370,37,53426913,2020-06-01 11:34:34,2020-06-01 12:15:34,1,3865,1,西東京店,TK,東京,東京,お持ち帰り
2,83379185,64,C71117940,93,4241579,2020-06-01 11:39:39,2020-06-01 12:18:39,0,3742,2,西東京店,TK,東京,東京,デリバリ
3,75647324,64,C98875469,35,28001375,2020-06-01 11:40:40,2020-06-01 11:51:40,0,2112,2,西東京店,TK,東京,東京,デリバリ
4,61658367,64,C97997460,27,19753684,2020-06-01 11:58:58,2020-06-01 12:29:58,0,698,2,西東京店,TK,東京,東京,デリバリ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703875,10044453,196,C22536742,29,18512545,2020-05-31 18:46:46,2020-05-31 18:56:46,1,3901,1,前橋店,GU,北関東,群馬,お持ち帰り
703876,69461367,196,C33554836,87,99552096,2020-05-31 19:21:21,2020-05-31 19:54:21,1,1927,1,前橋店,GU,北関東,群馬,お持ち帰り
703877,48225714,196,C33554836,96,22365732,2020-05-31 21:03:03,2020-05-31 21:33:03,0,2615,2,前橋店,GU,北関東,群馬,デリバリ
703878,76183473,196,C33554836,76,72014484,2020-05-31 21:04:04,2020-05-31 21:42:04,0,4659,2,前橋店,GU,北関東,群馬,デリバリ
703879,95868903,196,C07335754,12,78947363,2020-05-31 21:42:42,2020-05-31 22:24:42,0,2677,2,前橋店,GU,北関東,群馬,デリバリ

In [18]:
order_data["status_name"] = order_data["status"].map({0: "受付", 1: "お支払い済み", 2: "お渡し済み"})
order_data

,order_id,store_id,customer_id,coupon_cd,sales_detail_id,order_accept_date,delivered_date,takeout_flag,total_amount,status,store_name,area_cd,wide_area,narrow_area,takeout_name,status_name
0,16514392,64,C44271355,49,56527968,2020-06-01 11:00:00,2020-06-01 11:55:00,0,2732,2,西東京店,TK,東京,東京,デリバリ,お渡し済み
1,12865494,64,C14333370,37,53426913,2020-06-01 11:34:34,2020-06-01 12:15:34,1,3865,1,西東京店,TK,東京,東京,お持ち帰り,お支払い済み
2,83379185,64,C71117940,93,4241579,2020-06-01 11:39:39,2020-06-01 12:18:39,0,3742,2,西東京店,TK,東京,東京,デリバリ,お渡し済み
3,75647324,64,C98875469,35,28001375,2020-06-01 11:40:40,2020-06-01 11:51:40,0,2112,2,西東京店,TK,東京,東京,デリバリ,お渡し済み
4,61658367,64,C97997460,27,19753684,2020-06-01 11:58:58,2020-06-01 12:29:58,0,698,2,西東京店,TK,東京,東京,デリバリ,お渡し済み
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703875,10044453,196,C22536742,29,18512545,2020-05-31 18:46:46,2020-05-31 18:56:46,1,3901,1,前橋店,GU,北関東,群馬,お持ち帰り,お支払い済み
703876,69461367,196,C33554836,87,99552096,2020-05-31 19:21:21,2020-05-31 19:54:21,1,1927,1,前橋店,GU,北関東,群馬,お持ち帰り,お支払い済み
703877,48225714,196,C33554836,96,22365732,2020-05-31 21:03:03,2020-05-31 21:33:03,0,2615,2,前橋店,GU,北関東,群馬,デリバリ,お渡し済み
703878,76183473,196,C33554836,76,72014484,2020-05-31 21:04:04,2020-05-31 21:42:04,0,4659,2,前橋店,GU,北関東,群馬,デリバリ,お渡し済み
703879,95868903,196,C07335754,12,78947363,2020-05-31 21:42:42,2020-05-31 22:24:42,0,2677,2,前橋店,GU,北関東,群馬,デリバリ,お渡し済み